services:
  compiler:
    build:
      context: .
      dockerfile: Dockerfile
    image: stm32-cmake-env:0.1
    volumes:
      - ../:/workspace
    user: "${UID}:${GID}"
    command: tail -f /dev/null